deployment:
  tasks:
    - install_dependencies:
        command: npm install
        cwd: .
    - build_project:
        command: npm run build
        cwd: .
    - deploy_files:
        command: cp -r dist/* ~/public_html
        cwd: .
