deployment:
  tasks:
    - install_dependencies:
        command: ~/nodejs/bin/npm install
        cwd: .
    - build_project:
        command: ~/nodejs/bin/npm run build
        cwd: .
    - deploy_files:
        command: cp -r dist/* ~/public_html
        cwd: .
