deployment:
  tasks:
    - install_dependencies: npm install
    - build_project: npm run build
    - deploy_files:
        command: |
          rm -rf /home/elinixay/public_html/*
          cp -r dist/* /home/elinixay/public_html
